platform :ios, '9.0'
target 'Homework' do
  
pod 'MJRefresh'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'IQKeyboardManager'
pod 'SDCycleScrollView'
pod 'UMCCommon'
pod 'UMCSecurityPlugins'
pod 'UMCAnalytics'
pod 'UMCCommonLog'
pod 'UMCPush'
pod 'UMCShare/UI'
pod 'UMCShare/Social/ReducedWeChat'
pod 'UMCShare/Social/ReducedQQ'
pod 'UMCShare/Social/ReducedSina'
pod 'AlipaySDK-iOS'
pod 'RongCloudIM/IMLib'
pod 'RongCloudIM/IMKit'
pod 'RongCloudRTC/RongCallLib'
pod 'RongCloudRTC/RongCallKit'
pod 'AFNetworking'

end
